const $=id=>document.getElementById(id);
const challenges={unseen:{label:'Leaves unseen'},waiting:{label:'Loses momentum'},stalled:{label:'Conversation stalls'}};
let selectedChallenge='';
function selectChallenge(key){if(!Object.hasOwn(challenges,key))throw new Error('Unknown challenge');selectedChallenge=key;document.querySelectorAll('[data-challenge]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.challenge===key)));$('focus-status').textContent='Our focus: '+challenges[key].label;return{challenge:key,label:challenges[key].label};}
document.querySelectorAll('[data-challenge]').forEach(b=>b.addEventListener('click',()=>selectChallenge(b.dataset.challenge)));
$('section-jump').addEventListener('change',e=>{const section=$(e.target.value);if(section)location.hash=section.id;});
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)$('section-jump').value=entry.target.id;},{rootMargin:'-10% 0px -65% 0px',threshold:0});document.querySelectorAll('main section').forEach(s=>observer.observe(s));
const routes={
 compare:{question:'I want to keep working. Should I explore the part-time MBA or a specialized master’s?',reason:'This is a comparison. It needs information from both programs.',intent:['Program fit','Work schedule'],active:['mba','masters'],summary:'2 program specialists consulted',mba:['Study format, schedule, and workload','MBA program pages'],masters:['Study format, schedule, and workload','Master’s program pages'],result:'One useful comparison',text:'The student can compare how each program fits around work, without starting a separate conversation for each one.',points:['Study format','Schedule','Workload'],boundary:'Program details come from the institution’s published information.'},
 requirements:{question:'What do I need to apply for the part-time MBA?',reason:'The student named one program and asked about applying. Only the MBA specialist is needed.',intent:['Part-time MBA','Entry requirements'],active:['mba'],summary:'1 program specialist consulted',mba:['Published entry requirements and application documents','MBA admissions requirements'],result:'A clear application checklist',text:'The student learns which published requirements and documents to review before applying to the part-time MBA.',points:['Entry requirements','Required documents'],boundary:'Meeting published requirements does not guarantee admission.'},
 timing:{question:'When does the specialized master’s start, and when should I apply?',reason:'This is a timing question about the master’s. Route it to that program’s specialist.',intent:['Specialized master’s','Dates & deadlines'],active:['masters'],summary:'1 program specialist consulted',masters:['Published start dates and application deadlines','Master’s intake and deadline pages'],result:'Dates for the right program',text:'The student gets the relevant intake and application timing for the specialized master’s.',points:['Start dates','Application deadlines'],boundary:'If the available sources do not establish an answer, a person needs to help.'},
 exception:{question:'My background doesn’t meet a listed requirement. Could you make an exception?',reason:'This asks for a decision about an individual. Published program information cannot authorize an exception.',intent:['Individual situation','Exception request'],active:[],summary:'Hand off to admissions',human:true,result:'A person takes the next step',text:'Admissions receives the question and conversation context so a counselor can review the situation.',points:['Student’s question','Conversation context'],boundary:'The agent does not promise admission or approve exceptions.'}
};
function selectRoute(key){const r=routes[key];if(!r)throw new Error('Unknown route');document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===key)));$('route-question').textContent='“'+r.question+'”';$('route-reason').textContent=r.reason;$('route-intent').replaceChildren(...r.intent.map(text=>{const el=document.createElement('span');el.textContent=text;return el;}));$('route-summary').textContent=r.summary;$('human-route').hidden=!r.human;$('specialist-grid').hidden=!!r.human;
 for(const name of ['mba','masters']){const card=$(name+'-expert'),active=r.active.includes(name);card.classList.toggle('active',active);card.classList.toggle('inactive',!active);card.querySelector('.expert-status').textContent=active?'✓ Consulted':'Not needed';$(name+'-contribution').textContent=active?r[name][0]:'This question is about the other program.';card.querySelector('.expert-source').hidden=!active;if(active)$(name+'-source').textContent=r[name][1];}
 $('result-heading').textContent=r.result;$('route-result-text').textContent=r.text;$('result-boundary').textContent=r.boundary;$('result-points').replaceChildren(...r.points.map(text=>{const el=document.createElement('span');el.textContent=text;return el;}));return{question:r.question,consulted:r.human?['Admissions counselor']:r.active,result:r.result};}
document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>selectRoute(b.dataset.route)));
selectRoute('compare');
let draft='You mentioned wanting to keep working while studying. Would it help to talk through the part-time MBA options with an admissions counselor?';
const followupTemplate=$('review-panel').innerHTML;
function setScenario(key){document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===key)));if(key==='followup'){$('review-panel').innerHTML=followupTemplate;$('draft-message').textContent=draft;}else if(key==='deadline'){$('review-panel').innerHTML='<span class="review-label">Published information</span><h3>“When is the application due?”</h3><p>Answer from the program’s published deadline information.</p><div class="evidence"><strong>What supports the answer?</strong>The relevant program source and its current information.</div><p class="feedback">If the source does not establish the answer, the question needs further review.</p>';}else{$('review-panel').innerHTML='<span class="review-label">Human judgment</span><h3>“My qualification isn’t listed. Can I still apply?”</h3><p>Hand the question to admissions with the conversation attached.</p><div class="evidence"><strong>What helps the counselor?</strong>The student’s question, their stated background, and the program they are considering.</div><p class="feedback">An admissions counselor evaluates the individual situation.</p>';}}
 document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>setScenario(b.dataset.scenario)));
$('review-panel').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;const editor=$('draft-editor');if(editor)draft=editor.value;if(action==='edit'){if(!editor){const textarea=document.createElement('textarea');textarea.id='draft-editor';textarea.className='edit-area';textarea.setAttribute('aria-label','Edit the illustrative follow-up');textarea.maxLength=1500;textarea.value=draft;$('draft-message').replaceWith(textarea);}b.textContent='Save edit';b.dataset.action='save';$('draft-editor').focus();$('review-feedback').textContent='Adjust the wording, then save your edit.';}else if(action==='save'){const p=document.createElement('p');p.id='draft-message';p.className='review-message';p.textContent=draft;editor.replaceWith(p);b.textContent='Edit';b.dataset.action='edit';$('review-feedback').textContent='Your example draft is updated. It has not been sent.';}else{$('review-feedback').textContent=action==='approve'?'Approved in this illustration. In the product, your team approves the message before it is sent.':'Held in this illustration. The counselor can resolve questions before proceeding.';}});
// Agent actions use the same challenge selection as the visible Lab.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'select_recruitment_challenge',description:'Select the recruitment challenge to explore and update the visible Lab focus.',inputSchema:{type:'object',properties:{challenge:{type:'string',enum:['unseen','waiting','stalled']}},required:['challenge'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>k!=='challenge'))throw new Error('Supply only a valid challenge');return selectChallenge(input.challenge);}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
