'use strict';
const $=id=>document.getElementById(id);
const scenarios={
 academic:{name:'Academic progress',primary:2,threshold:5,min:1,max:13,observed:6,unit:'days',mode:'elapsed',fact:'Alex has not logged in for <strong>6 days.</strong>',triggerLabel:'Flag after this many days without a login',triggerNote:'Try 7 days. Alex’s six days of inactivity stays the same, but the signal is no longer active.',reason:n=>`6 days without a login ${6>=n?'meets':'does not meet'} your ${n}-day rule.`,signals:[
 {label:'Missed assignment',weight:10,day:'MON',event:'Assignment missed',detail:'One piece of coursework is overdue.',category:'Coursework',reason:'One missed assignment is active in this example.'},
 {label:'Grade below floor',weight:20,day:'WED',event:'Grade below the floor',detail:'A course grade of 62% is below the example floor of 70%.',category:'Grades',reason:'62% is below the example grade floor of 70%.'},
 {label:'Engagement drop',weight:20,day:'FRI',event:'Six days without a login',detail:'A change in engagement adds context.',category:'Engagement',reason:'Uses the inactivity trigger from section 2.'}],priority:'Understand what is affecting coursework and reconnect Alex with support.',deadline:'Next assignment due in 3 days.',question:'“How have things been going with your coursework this week?”'},
 engagement:{name:'Engagement',primary:0,threshold:5,min:1,max:13,observed:6,unit:'days',mode:'elapsed',fact:'Alex has not logged in for <strong>6 days.</strong>',triggerLabel:'Flag after this many days without a login',triggerNote:'Try 7 days. The inactivity signal switches off; the other warning signs still contribute.',reason:n=>`6 days without a login ${6>=n?'meets':'does not meet'} your ${n}-day rule.`,signals:[
 {label:'Engagement drop',weight:20,day:'MON',event:'Six days without a login',detail:'The course activity record shows a gap.',category:'Engagement',reason:'Uses the inactivity trigger from section 2.'},
 {label:'No response to outreach',weight:10,day:'WED',event:'A check-in goes unanswered',detail:'The previous outreach has not received a reply.',category:'Outreach',reason:'No reply to the previous check-in is active in this example.'},
 {label:'No advisor meeting',weight:5,day:'FRI',event:'A gap in advisor contact',detail:'No advisor meeting is recorded in 60 days.',category:'Advising',reason:'No recorded advisor meeting in 60 days is active in this example.'}],priority:'Find out whether Alex can access the course and what would help them reconnect.',deadline:'Next scheduled course check-in is Friday.',question:'“We haven’t connected recently. Is there something making it harder to take part?”'},
 registration:{name:'Registration',primary:1,threshold:30,min:7,max:45,observed:28,unit:'days',mode:'remaining',fact:'Alex is not registered. The deadline is in <strong>28 days.</strong>',triggerLabel:'Flag nonregistration within this many days of the deadline',triggerNote:'Try 14 days. With 28 days remaining, Alex is outside that warning window. The other signals still count.',reason:n=>`28 days remaining is ${28<=n?'inside':'outside'} your ${n}-day warning window.`,signals:[
 {label:'Financial hold',weight:25,day:'MON',event:'An unresolved financial hold',detail:'A soft hold needs attention before it becomes a registration block.',category:'Finances',reason:'A soft financial hold adds the configured points. A registration-blocking hold is a different condition.'},
 {label:'Not registered next term',weight:20,day:'WED',event:'Next term is not registered',detail:'The registration deadline is 28 days away.',category:'Registration',reason:'Uses the registration warning window from section 2.'},
 {label:'No response to outreach',weight:10,day:'FRI',event:'No reply to the check-in',detail:'Previous outreach has not received a response.',category:'Outreach',reason:'No reply to the previous check-in is active in this example.'}],priority:'Understand the hold and connect Alex with the team that can help resolve it.',deadline:'Registration closes in 28 days.',question:'“Is something getting in the way of registering for next term? Let’s work out who can help.”'}
};
let current='academic',state;
function scenario(){return scenarios[current];}
function primaryActive(){const c=scenario();return c.mode==='remaining'?c.observed<=state.threshold:c.observed>=state.threshold;}
function active(i){return i===scenario().primary?primaryActive():state.enabled[i];}
function total(){return state.weights.reduce((s,w,i)=>s+(active(i)?w:0),0);}
function bands(){return [{key:'low',name:'Low',min:0,max:29,action:'No action'},{key:'moderate',name:'Moderate',min:30,max:49,action:'Early nudge'},{key:'high',name:'High',min:50,max:state.escalation-1,action:'Outreach email'},{key:'critical',name:'Critical',min:state.escalation,max:89,action:'Advisor escalation + meeting'},{key:'emergency',name:'Emergency',min:90,max:Infinity,action:'Dean/advisor escalation'}];}
function bandFor(score){return bands().find(b=>score>=b.min&&score<=b.max);}
function reset(key=current,feedback=''){current=key;const c=scenario();state={threshold:c.threshold,enabled:c.signals.map(()=>true),weights:c.signals.map(s=>s.weight),escalation:70};document.querySelectorAll('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===current)));$('trigger-threshold').min=c.min;$('trigger-threshold').max=c.max;$('trigger-threshold').value=c.threshold;$('escalation-threshold').value=70;$('trigger-fact').innerHTML=c.fact;$('trigger-label').textContent=c.triggerLabel;$('trigger-note').textContent=c.triggerNote;$('axis-min').textContent=c.min+' days';$('axis-max').textContent=c.max+' days';$('student-marker').style.left=(c.observed-c.min)/(c.max-c.min)*100+'%';$('student-marker').innerHTML=`<span>Alex<br><b>${c.observed} days</b></span>`;$('signal-rows').innerHTML=c.signals.map((s,i)=>`<div class="signal-row" id="signal-${i}"><div class="signal-heading">${i===c.primary?`<span>${s.label}</span>`:`<label><input type="checkbox" id="signal-toggle-${i}" data-toggle="${i}" checked>${s.label}</label>`}</div><p class="signal-status" id="signal-status-${i}">${i===c.primary?'<a href="#triggers">Uses your trigger above ↑</a>':'Included in this example'}</p><div class="weight-control"><label for="weight-${i}">Points when active</label><input type="number" id="weight-${i}" data-weight="${i}" min="0" max="50" step="5" value="${s.weight}" aria-label="${s.label}: points when active" aria-describedby="weight-error-${i}"><span>pts</span></div><p id="weight-error-${i}" class="invalid-hint" hidden>Choose 0–50 points, in steps of 5.</p><div class="point-track" aria-hidden="true"><span class="point-fill" id="point-fill-${i}" style="width:${s.weight*2}%"></span></div><div class="point-caption"><span id="point-state-${i}">Active signal</span><strong id="contribution-${i}">+${s.weight}</strong></div></div>`).join('');render(feedback);}
function render(message=''){
 const c=scenario(),score=total(),band=bandFor(score),primary=primaryActive();
 $('week').innerHTML=c.signals.map((s,i)=>`<li><span class="day">${s.day}</span><div><strong>${s.event}</strong><p>${s.detail}</p><span class="signal-chip ${active(i)?'':'chip-off'}">${active(i)?s.category+' · Active':i===c.primary?'Outside your trigger':'Not included in the score'}</span></div></li>`).join('');
 $('trigger-value').textContent=state.threshold+' days';$('threshold-marker').style.left=(state.threshold-c.min)/(c.max-c.min)*100+'%';$('threshold-marker').innerHTML=`<span>Your rule<br><b>${state.threshold} days</b></span>`;$('threshold-plot').setAttribute('aria-label',c.reason(state.threshold));$('trigger-result').classList.toggle('active',primary);$('trigger-result').innerHTML=`<strong>${primary?'✓ Signal active':'Condition not yet met'}</strong><p>${c.reason(state.threshold)}</p>`;
 $('score-scenario').textContent='ALEX · '+c.name.toUpperCase();
 c.signals.forEach((s,i)=>{const on=active(i);$('signal-'+i).classList.toggle('inactive',!on);$('point-fill-'+i).style.width=(on?state.weights[i]*2:0)+'%';$('point-state-'+i).textContent=on?'Active signal':'Not active · adds 0';$('contribution-'+i).textContent='+'+(on?state.weights[i]:0);if(i!==c.primary)$('signal-status-'+i).textContent=on?'Included in this example':'Excluded from this example';});
 const equation=c.signals.map((s,i)=>active(i)?state.weights[i]:0).join(' + ');$('equation').textContent=equation;$('total').textContent=score;$('score-band').innerHTML=band.name+'<span>'+band.action+'</span>';$('score-feedback').textContent=message||`${equation} = ${score} points.`;
 $('ladder-score').textContent=score;$('escalation-value').textContent=state.escalation+' pts';$('ladder').innerHTML=bands().map(b=>`<li data-band="${b.key}" class="${b.key===band.key?'is-current':''}" ${b.key===band.key?'aria-current="true"':''}><div class="band-top"><strong>${b.name}</strong><span>${b.max===Infinity?'90+':b.min+'–'+b.max} points</span></div><p>${b.action}</p>${b.key===band.key?`<span class="current-label">← Alex is here · ${score} points</span>`:''}</li>`).join('');$('threshold-feedback').textContent=`${score} points ${score>=state.escalation?'meets':'is below'} the ${state.escalation}-point advisor threshold. Response: ${band.action.toLowerCase()}.`;
 const count=c.signals.filter((s,i)=>active(i)).length;$('advisor-score').textContent=`Alex has ${score} points from ${count} active warning ${count===1?'sign':'signs'}. ${band.name}: ${band.action.toLowerCase()}.`;
 // Keep expanded reasons open while another control updates the score.
 const open=new Set(Array.from($('advisor-signals').querySelectorAll('details[open]')).map(d=>d.dataset.signal));
 $('advisor-signals').innerHTML=c.signals.map((s,i)=>active(i)?`<details class="signal-reason" data-signal="${i}" ${open.has(String(i))?'open':''}><summary>${s.label} · +${state.weights[i]}</summary><p>${i===c.primary?c.reason(state.threshold):s.reason} Your example weight adds ${state.weights[i]} points.</p></details>`:'').join('')||'<p class="small">No warning signs are active in this example.</p>';$('advisor-priority').textContent=c.priority;$('advisor-deadline').textContent=c.deadline;$('conversation-question').textContent=c.question;
}
document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>reset(b.dataset.scenario,'New scenario selected. The points and thresholds have returned to its starting example.')));
$('trigger-threshold').addEventListener('input',e=>{state.threshold=Number(e.target.value);render('Your trigger changed. Only active signals contribute to the total.');});
$('signal-rows').addEventListener('change',e=>{if(e.target.dataset.toggle!==undefined){state.enabled[Number(e.target.dataset.toggle)]=e.target.checked;render('The warning signs included in our example changed. The weights stayed the same.');}});
$('signal-rows').addEventListener('input',e=>{if(e.target.dataset.weight===undefined)return;const i=Number(e.target.dataset.weight),n=e.target.valueAsNumber,valid=Number.isFinite(n)&&n>=0&&n<=50&&n%5===0;e.target.setAttribute('aria-invalid',String(!valid));$('weight-error-'+i).hidden=valid;if(!valid)return;const before=total();state.weights[i]=n;const diff=total()-before;render(diff?`The total ${diff>0?'increased':'decreased'} by ${Math.abs(diff)} because you changed the points for ${scenario().signals[i].label.toLowerCase()}.`:active(i)?'The total stayed the same.':'The weight changed. An inactive signal still contributes 0 points.');});
$('signal-rows').addEventListener('focusout',e=>{if(e.target.dataset.weight===undefined||e.target.getAttribute('aria-invalid')!=='true')return;const i=Number(e.target.dataset.weight);e.target.value=state.weights[i];e.target.setAttribute('aria-invalid','false');$('weight-error-'+i).hidden=true;});
$('reset-example').addEventListener('click',()=>reset(current,'Restored this scenario’s starting signals, weights, and action thresholds.'));
$('escalation-threshold').addEventListener('input',e=>{state.escalation=Number(e.target.value);render('The action threshold changed. Alex’s total points stayed the same.');});
$('compare-threshold').addEventListener('click',()=>{reset('academic');state.weights[2]=30;$('weight-2').value=30;render('Comparison example: 10 + 20 + 30 = 60 points. Now move the advisor threshold from 70 to 60.');$('threshold-feedback').textContent='Alex is at 60 points. Move the advisor threshold from 70 to 60 to see the response change.';});
$('contact-gap').addEventListener('input',e=>{const gap=Number(e.target.value),eligible=gap<=1;$('contact-gap-value').textContent=gap+' '+(gap===1?'day':'days');$('repeat-result').textContent=eligible?'1 day since outreach. Another automated contact is eligible if it is still needed.':'1 day since outreach. Wait before another automated message.';$('repeat-chip').textContent=eligible?'Spacing rule met':'Repeat contact limited';$('next-contact-day').textContent=['','TUE','WED','THU','FRI','SAT'][gap];$('next-contact-detail').textContent=`After ${gap} ${gap===1?'day':'days'}, recheck the situation before sending again.`;});
$('repeat-result').setAttribute('aria-live','polite');
$('section-jump').addEventListener('change',e=>{const id=e.target.value;history.pushState(null,'','#'+id);document.getElementById(id).scrollIntoView();});
let scrollPending=false;
window.addEventListener('scroll',()=>{if(scrollPending)return;scrollPending=true;requestAnimationFrame(()=>{scrollPending=false;const line=document.querySelector('.section-nav').getBoundingClientRect().height+70;let id='barriers';document.querySelectorAll('main section').forEach(section=>{if(section.getBoundingClientRect().top<=line)id=section.id;});$('section-jump').value=id;});},{passive:true});

reset();

if('ResizeObserver' in window)new ResizeObserver(entries=>{document.documentElement.style.setProperty('--section-nav-height',Math.ceil(entries[0].target.getBoundingClientRect().height)+8+'px');}).observe(document.querySelector('.section-nav'));
