'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const titles={signals:['Student signals','Signals across the student journey'],triggers:['Institution’s triggers','The institution sets the conditions'],points:['Points and total','How the contributions add up'],thresholds:['Response thresholds','From total to response'],outreach:['Coordinated outreach','Coordinate around the contact history'],advisor:['Advisor context','The context behind the conversation'],intervention:['Early intervention','Early identification and intervention']};
let opener=null,expanded=false,wireFrame;
function positionStack(){const canvas=$('.workflow-canvas'),height=innerWidth<650?310:innerWidth<1050?325:340;$$('.workflow-node').forEach(el=>{el.style.setProperty('--fold-x',((canvas.clientWidth-el.offsetWidth)/2-el.offsetLeft)+'px');el.style.setProperty('--fold-y',((height-el.offsetHeight)/2+17-el.offsetTop)+'px');});}
function drawWires(){positionStack();const canvas=$('.workflow-canvas'),base=canvas.getBoundingClientRect(),nodes=$$('.workflow-node').map(el=>el.getBoundingClientRect());$('.workflow-wires').setAttribute('viewBox',`0 0 ${base.width} ${base.height}`);for(let i=0;i<nodes.length-1;i++){const a=nodes[i],b=nodes[i+1],horizontal=b.left>=a.right+6,ax=(horizontal?a.right:a.left+a.width/2)-base.left,ay=(horizontal?a.top+a.height/2:a.top)-base.top,bx=(horizontal?b.left:b.left+b.width/2)-base.left,by=(horizontal?b.top+b.height/2:b.bottom)-base.top;$('#wire-'+i).setAttribute('d',`M ${ax+(horizontal?3:0)} ${ay-(horizontal?0:4)} L ${bx-(horizontal?4:0)} ${by+(horizontal?0:8)}`);}}
function setExpanded(value,{focus=false}={}){expanded=value;positionStack();const canvas=$('.workflow-canvas');canvas.classList.toggle('is-collapsed',!value);$$('.workflow-node').forEach(el=>{el.tabIndex=value?0:-1;el.setAttribute('aria-hidden',String(!value));});$('.stack-cover').hidden=value;$('#replay').innerHTML=value?'Collapse layers <span aria-hidden="true">↙</span>':'Expand layers <span aria-hidden="true">↗</span>';$('#replay').setAttribute('aria-expanded',String(value));$('#replay').setAttribute('aria-label',value?'Collapse retention flow':'Expand retention flow');$('#flow-instruction').textContent=value?'Select any stage':'Expand the flow';cancelAnimationFrame(wireFrame);const end=performance.now()+1000;function frame(){drawWires();if(performance.now()<end)wireFrame=requestAnimationFrame(frame);}frame();if(focus)$('#replay').focus({preventScroll:true});}
function openStage(id){if(!titles[id])return;if(!expanded)setExpanded(true);opener=$(`[data-stage="${id}"]`);$$('[data-panel]').forEach(el=>el.hidden=el.dataset.panel!==id);$$('[data-stage]').forEach(el=>{el.setAttribute('aria-expanded',String(el===opener));if(el===opener)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});$('#panel-kicker').textContent=`0${Object.keys(titles).indexOf(id)+1} / ${titles[id][0]}`;$('#panel-title').textContent=titles[id][1];if(!$('#step-panel').open)$('#step-panel').showModal();$('.step-popup-body').scrollTop=0;$('#panel-title').focus({preventScroll:true});history.replaceState(null,'','#'+id);}
$$('[data-stage]').forEach((el,i)=>{el.style.setProperty('--i',i);el.addEventListener('click',()=>openStage(el.dataset.stage));});
$('#close-step').addEventListener('click',()=>$('#step-panel').close());
$('#step-panel').addEventListener('close',()=>{$$('[data-stage]').forEach(el=>{el.setAttribute('aria-expanded','false');el.removeAttribute('aria-current');});history.replaceState(null,'','#flow');opener?.focus({preventScroll:true});});
$('#step-panel').addEventListener('click',e=>{if(e.target!==$('#step-panel'))return;const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();});
$('#step-panel').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();$('#close-step').focus();}});
$('#replay').addEventListener('click',()=>setExpanded(!expanded));$('#expand-cover').addEventListener('click',()=>setExpanded(true,{focus:true}));new ResizeObserver(drawWires).observe($('.workflow-canvas'));window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(titles[id])openStage(id);else if($('#step-panel').open)$('#step-panel').close();});
setExpanded(false);if(titles[location.hash.slice(1)])openStage(location.hash.slice(1));
